CREATE DATABASE `cloud_bill` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

use `cloud_bill`;

CREATE TABLE IF NOT EXISTS `aliyun_bill_resource_summary` (
  `id` int AUTO_INCREMENT NOT NULL ,
  `bill_month` datetime NULL COMMENT '账单归属月',
  `adjust_amount` decimal(18,8) NULL COMMENT '信用额度退款抵扣',
  `bill_account_id` varchar(50) NULL COMMENT '账单所属账号ID',
  `bill_account_name` varchar(50) NULL COMMENT '账单所属账号名称',
  `billing_date` datetime NULL COMMENT '账单日期',
  `billing_item` varchar(20) NULL COMMENT '计费项',
  `billing_item_code` varchar(20) NULL COMMENT '计费项代码',
  `billing_type` varchar(20) NULL COMMENT '计费方式',
  `biz_type` varchar(20) NULL COMMENT '业务类型',
  `cash_amount` decimal(18,8) NULL COMMENT '现金支付（不包含信用额度退款抵扣）',
  `commodity_code` varchar(50) NULL COMMENT '商品Code',
  `cost_unit` varchar(50) NULL COMMENT '财务单元',
  `currency` varchar(20) NULL COMMENT '币种',
  `deducted_by_cash_coupons` decimal(18,8) NULL COMMENT '代金券抵扣',
  `deducted_by_coupons` decimal(18,8) NULL COMMENT '优惠券优惠金额',
  `deducted_by_prepaid_card` decimal(18,8) NULL COMMENT '储值卡抵扣',
  `deducted_by_resource_package` varchar(255) NULL COMMENT '资源包抵扣',
  `instance_config` text NULL COMMENT '实例详细配置',
  `instance_id` varchar(100) NULL COMMENT '实例ID',
  `instance_spec` varchar(255) NULL COMMENT '实例规格',
  `internet_ip` varchar(50) NULL COMMENT '公网IP',
  `intranet_ip` varchar(50) NULL COMMENT '私网IP',
  `invoice_discount` decimal(18,8) NULL COMMENT '优惠金额',
  `item` varchar(20) NULL COMMENT '账单类型',
  `item_name` varchar(20) NULL COMMENT '项目名称',
  `list_price` decimal(18,8) NULL COMMENT '单价',
  `list_price_unit` varchar(20) NULL COMMENT '单价单位',
  `nick_name` varchar(200) NULL COMMENT '实例昵称',
  `outstanding_amount` decimal(18,8) NULL COMMENT '未结清金额',
  `owner_id` varchar(50) NULL COMMENT '资源Owner账号',
  `payment_amount` decimal(18,8) NULL COMMENT '现金支付（含信用额度退款抵扣）',
  `pip_code` varchar(50) NULL COMMENT '产品Code',
  `pretax_amount` decimal(18,8) NULL COMMENT '应付金额',
  `pretax_gross_amount` decimal(18,8) NULL COMMENT '原始金额',
  `discount` decimal(3,2) NULL COMMENT '折扣率：本资源享受的折扣率，接口未提供，计算公式：pretax_amount/pretax_gross_amount',
  `product_code` varchar(50) NULL COMMENT '产品代码',
  `product_detail` varchar(255) NULL COMMENT '产品明细',
  `product_name` varchar(50) NULL COMMENT '产品名称',
  `product_type` varchar(50) NULL COMMENT '产品类型',
  `region` varchar(100) NULL COMMENT '地域',
  `resource_group` varchar(50) NULL COMMENT '资源组',
  `service_period` int NULL COMMENT '服务时长',
  `service_period_unit` varchar(20) NULL COMMENT '服务时长单位',
  `subscription_type` varchar(20) NULL COMMENT '订阅类型(Subscription预付费,PayAsYouGo后付费)',
  `tag` varchar(255) NULL COMMENT '资源标签',
  `usage` decimal(18,8) NULL COMMENT '用量',
  `usage_unit` varchar(20) NULL COMMENT '用量单位',
  `zone` varchar(50) NULL COMMENT '可用区',
  PRIMARY KEY (`id`),
  INDEX `idx_bill_month_account` (`bill_month`,`bill_account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS `tencent_bill_resource_summary` (
  `id` int AUTO_INCREMENT NOT NULL ,
  `bill_month` datetime NULL COMMENT '账单归属月',
  `tags` json NULL COMMENT '标签信息，注意：此字段可能返回 null，表示取不到有效值。',
  `action_type_name` varchar(50) NULL COMMENT '交易类型：如包年包月新购、包年包月续费、按量计费扣费等类型',
  `business_code` varchar(50) NULL COMMENT '产品编码',
  `business_code_name` varchar(100) NULL COMMENT '产品名称：用户所采购的各类云产品，例如：云服务器 CVM',
  `cash_pay_amount` decimal(18,8) NULL COMMENT '现金账户支出：通过现金账户支付的金额',
  `config_desc` varchar(255) NULL COMMENT '配置描述：该资源下的计费项名称和用量合并展示，仅在资源账单体现',
  `discount` decimal(3,2) NULL COMMENT '折扣率：本资源享受的折扣率（如果客户享受一口价/合同价则默认不展示，退费场景也默认不展示）',
  `extend_field1` varchar(255) NULL COMMENT '扩展字段1：产品对应的扩展属性信息，仅在资源账单体现',
  `extend_field2` varchar(255) NULL COMMENT '扩展字段2：产品对应的扩展属性信息，仅在资源账单体现',
  `extend_field3` varchar(255) NULL COMMENT '扩展字段3：产品对应的扩展属性信息，仅在资源账单体现',
  `extend_field4` varchar(255) NULL COMMENT '扩展字段4：产品对应的扩展属性信息，仅在资源账单体现',
  `extend_field5` varchar(255) NULL COMMENT '扩展字段5：产品对应的扩展属性信息，仅在资源账单体现',
  `fee_begin_time` datetime NULL COMMENT '开始使用时间：产品服务开始使用时间',
  `fee_end_time` datetime NULL COMMENT '结束使用时间：产品服务结束使用时间',
  `incentive_pay_amount` decimal(18,8) NULL COMMENT '赠送账户支出：使用赠送金支付的金额',
  `instance_type` varchar(50) NULL COMMENT '实例类型：购买的产品服务对应的实例类型，包括资源包、RI、SP、竞价实例。正常的实例展示默认为不展示',
  `operate_uin` varchar(30) NULL COMMENT '操作者UIN：操作者账号 ID（预付费资源下单或后付费操作开通资源账号的 ID 或者角色 ID ）',
  `order_id` varchar(30) NULL COMMENT '订单ID：包年包月计费模式下订购的订单号',
  `original_cost_with_ri` decimal(18,8) NULL COMMENT '预留实例抵扣组件原价：本产品或服务使用预留实例抵扣的组件原价金额',
  `original_cost_with_sp` decimal(18,8) NULL COMMENT '节省计划抵扣组件原价：节省计划抵扣原价=节省计划包抵扣金额/节省计划抵扣率',
  `owner_uin` varchar(30) NULL COMMENT '使用者UIN：实际使用资源的账号 ID',
  `pay_mode_name` varchar(20) NULL COMMENT '计费模式：资源的计费模式，区分为包年包月和按量计费',
  `pay_time` datetime NULL COMMENT '扣费时间：结算扣费时间',
  `payer_uin` varchar(30) NULL COMMENT '支付者UIN：支付者的账号 ID，账号 ID 是用户在腾讯云的唯一账号标识',
  `product_code` varchar(50) NULL COMMENT '子产品编码',
  `product_code_name` varchar(100) NULL COMMENT '子产品名称：用户采购的具体产品细分类型，例如：云服务器 CVM-标准型 S1',
  `project_name` varchar(50) NULL COMMENT '项目名称：资源归属的项目，用户在控制台给资源自主分配项目，未分配则是默认项目',
  `real_total_cost` decimal(18,8) NULL COMMENT '优惠后总价',
  `reduce_type` varchar(20) NULL COMMENT '优惠类型',
  `region_id` int NULL COMMENT '地域ID',
  `region_name` varchar(100) NULL COMMENT '地域：资源所属地域，如华南地区（广州）',
  `resource_id` varchar(255) NULL COMMENT '资源 ID：账单中出账对象 ID，不同产品因资源形态不同，资源内容不完全相同，如云服务器 CVM 为对应的实例 ID',
  `resource_name` varchar(255) NULL COMMENT '资源别名：用户在控制台为资源设置的名称，如果未设置，则默认为空',
  `total_cost` decimal(18,8) NULL COMMENT '原价：原价 = 组件刊例价 * 组件用量 * 使用时长（如果客户享受一口价/合同价则默认不展示，退费类场景也默认不展示）',
  `transfer_pay_amount` decimal(18,8) NULL COMMENT '分成金账户支出：通过分成金账户支付的金额,注意：此字段可能返回 null，表示取不到有效值。',
  `voucher_pay_amount` decimal(18,8) NULL COMMENT '优惠券支出：使用各类优惠券（如代金券、现金券等）支付的金额',
  `zone_name` varchar(50) NULL COMMENT '可用区：资源所属可用区，如广州三区',
  PRIMARY KEY (`id`),
  INDEX `idx_bill_month_account` (`bill_month`,`owner_uin`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS `ucloud_bill_resource_summary` (
  `id` int AUTO_INCREMENT NOT NULL ,
  `bill_month` datetime NULL COMMENT '账单归属月',
  `admin` int NULL COMMENT '是否为主账号',
  `amount` decimal(18,8) NULL COMMENT '订单总金额',
  `amount_coupon` decimal(18,8) NULL COMMENT '代金券抵扣',
  `amount_free` decimal(18,8) NULL COMMENT '赠送金额抵扣',
  `amount_real` decimal(18,8) NULL COMMENT '现金账户支付',
  `az_group_c_name` varchar(50) NULL COMMENT '可用区',
  `charge_type` varchar(50) NULL COMMENT '计费方式: Year按年,Month按月,Day按天,Dynamic按时,Used按量,Donate赠送,Trial试用,Post后付费,Spot抢占式',
  `create_time` datetime NULL COMMENT '创建时间',
  `item_details` varchar(255) NULL COMMENT '产品配置',
  `order_no` varchar(50) NULL COMMENT '订单号',
  `order_type` varchar(50) NULL COMMENT '订单类型: OT_BUY新购,OT_RENEW续费,OT_UPGRADE升级,OT_DOWNGRADE降级,OT_SUSPEND结算,OT_ADDITIONAL补单  OT_REFUND删除,OT_POSTPAID_RENEW过期,OT_POSTPAID_PAYMENT后付费,OT_RECOVER删除恢复',
  `project_name` varchar(50) NULL COMMENT '项目名称',
  `resource_extend_info` varchar(255) NULL COMMENT '资源标识',
  `resource_id` varchar(50) NULL COMMENT '资源ID',
  `resource_type` varchar(50) NULL COMMENT '产品类型: uhost云主机,udisk普通云硬盘,udb云数据库,eip弹性IP,ufile对象存储,fortress_host堡垒机  ufs文件存储,wafWEB应用防火墙,ues弹性搜索,udisk_ssdSSD云硬盘,rssdRSSD云硬盘',
  `resource_type_code` int NULL COMMENT '产品类型代码',
  `show_hover` int NULL COMMENT '订单支付状态: 0未支付,1已支付',
  `start_time` datetime NULL COMMENT '开始时间',
  `user_display_name` varchar(50) NULL COMMENT '账户昵称',
  `user_email` varchar(50) NULL COMMENT '账户邮箱',
  `user_name` varchar(50) NULL COMMENT '账户名',
  `bill_account_id` varchar(50) NULL COMMENT '账单所属账号ID',
  PRIMARY KEY (`id`),
  INDEX `idx_bill_month_account` (`bill_month`,`bill_account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS `aws_bill_resource_summary` (
  `id` int AUTO_INCREMENT NOT NULL ,
  `bill_month` datetime NULL COMMENT '账单归属月',
  `service` varchar(100) NULL COMMENT '服务名称',
  `region` varchar(100) NULL COMMENT '地域',
  `unblended_cost` decimal(18,8) NULL COMMENT '未混合成本(美元)',
  `exchange_rate` decimal(8,4) NOT NULL COMMENT '汇率，非aws提供，仅供参考',
  `bill_account_id` varchar(50) NULL COMMENT '账单所属账号ID',
  PRIMARY KEY (`id`),
  INDEX `idx_bill_month_account` (`bill_month`,`bill_account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `volcengine_bill_resource_summary` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID,非api提供',
  `bill_month` datetime NULL COMMENT '账单归属月,非api提供',
  `bill_category` VARCHAR(50) DEFAULT NULL COMMENT '账单类别',
  `bill_detail_id` VARCHAR(100) DEFAULT NULL COMMENT '账单明细ID',
  `bill_id` VARCHAR(100) DEFAULT NULL COMMENT '账单ID',
  `bill_period` VARCHAR(7) NOT NULL COMMENT '账单年月，格式：YYYY-MM',
  `billing_function` VARCHAR(50) DEFAULT NULL COMMENT '单价价格类型',
  `billing_method_code` VARCHAR(50) DEFAULT NULL COMMENT '计费方式',
  `billing_mode` VARCHAR(50) DEFAULT NULL COMMENT '计费模式',
  `busi_period` VARCHAR(7) DEFAULT NULL COMMENT '业务账期',
  `business_mode` VARCHAR(50) DEFAULT NULL COMMENT '业务模式',
  `config_name` VARCHAR(255) DEFAULT NULL COMMENT '配置名称',
  `configuration_code` VARCHAR(255) DEFAULT NULL COMMENT '配置代码',
  `count` VARCHAR(50) DEFAULT NULL COMMENT '用量',
  `country_region` VARCHAR(100) DEFAULT NULL COMMENT '国家地区',
  `coupon_amount` DECIMAL(20,6) DEFAULT NULL COMMENT '优惠券金额',
  `credit_carried_amount` DECIMAL(20,6) DEFAULT NULL COMMENT '信控额度退款抵扣',
  `currency` VARCHAR(10) DEFAULT NULL COMMENT '货币类型',
  `currency_settlement` VARCHAR(10) DEFAULT NULL COMMENT '结算币种',
  `deduction_count` VARCHAR(50) DEFAULT NULL COMMENT '资源包抵扣量',
  `deduction_use_duration` VARCHAR(50) DEFAULT NULL COMMENT '资源包抵扣时长',
  `discount_bill_amount` DECIMAL(20,6) DEFAULT NULL COMMENT '折扣金额',
  `discount_biz_billing_function` VARCHAR(50) DEFAULT NULL COMMENT '优惠类型',
  `discount_biz_measure_interval` VARCHAR(255) DEFAULT NULL COMMENT '优惠用量区间',
  `discount_biz_unit_price` VARCHAR(50) DEFAULT NULL COMMENT '优惠价格/折扣',
  `discount_biz_unit_price_interval` VARCHAR(255) DEFAULT NULL COMMENT '优惠价格区间',
  `discount_info` VARCHAR(500) DEFAULT NULL COMMENT '优惠信息',
  `effective_factor` VARCHAR(50) DEFAULT NULL COMMENT '有效因子',
  `element` VARCHAR(255) DEFAULT NULL COMMENT '计费单元',
  `element_code` VARCHAR(50) DEFAULT NULL COMMENT '计费单元代码',
  `exchange_rate` DECIMAL(20,6) DEFAULT NULL COMMENT '汇率',
  `expand_field` VARCHAR(500) DEFAULT NULL COMMENT '扩展字段',
  `expense_begin_time` VARCHAR(20) DEFAULT NULL COMMENT '消费开始时间',
  `expense_date` VARCHAR(10) DEFAULT NULL COMMENT '消费日期，格式：YYYY-MM-DD',
  `expense_end_time` VARCHAR(20) DEFAULT NULL COMMENT '消费结束时间',
  `factor` VARCHAR(255) DEFAULT NULL COMMENT '影响因子',
  `factor_code` VARCHAR(255) DEFAULT NULL COMMENT '影响因子代码',
  `formula` VARCHAR(500) DEFAULT NULL COMMENT '应付金额计费公式',
  `instance_name` VARCHAR(255) DEFAULT NULL COMMENT '实例名称',
  `instance_no` VARCHAR(100) DEFAULT NULL COMMENT '实例编号',
  `main_contract_number` VARCHAR(100) DEFAULT NULL COMMENT '合同号',
  `market_price` VARCHAR(50) DEFAULT NULL COMMENT '市场价',
  `measure_interval` VARCHAR(255) DEFAULT NULL COMMENT '单价用量区间',
  `original_bill_amount` DECIMAL(20,6) DEFAULT NULL COMMENT '原价',
  `original_order_no` VARCHAR(100) DEFAULT NULL COMMENT '原订单号',
  `owner_customer_name` VARCHAR(255) DEFAULT NULL COMMENT '所有者客户名称',
  `owner_id` VARCHAR(50) DEFAULT NULL COMMENT '所有者ID',
  `owner_user_name` VARCHAR(255) DEFAULT NULL COMMENT '所有者用户名',
  `paid_amount` DECIMAL(20,6) DEFAULT NULL COMMENT '已付金额',
  `payable_amount` DECIMAL(20,6) DEFAULT NULL COMMENT '应付金额',
  `payer_customer_name` VARCHAR(255) DEFAULT NULL COMMENT '支付者客户名称',
  `payer_id` VARCHAR(50) DEFAULT NULL COMMENT '支付者ID',
  `payer_user_name` VARCHAR(255) DEFAULT NULL COMMENT '支付者用户名',
  `posttax_amount` DECIMAL(20,6) DEFAULT NULL COMMENT '税后应付金额',
  `pre_tax_payable_amount` DECIMAL(20,6) DEFAULT NULL COMMENT '税前应付金额（定价币种）',
  `preferential_bill_amount` DECIMAL(20,6) DEFAULT NULL COMMENT '优惠金额',
  `pretax_amount` DECIMAL(20,6) DEFAULT NULL COMMENT '税前应付金额',
  `pretax_real_value` VARCHAR(50) DEFAULT NULL COMMENT '税前真实金额',
  `price` VARCHAR(50) DEFAULT NULL COMMENT '单价',
  `price_interval` VARCHAR(255) DEFAULT NULL COMMENT '单价价格区间',
  `price_unit` VARCHAR(50) DEFAULT NULL COMMENT '单价单位',
  `product` VARCHAR(100) DEFAULT NULL COMMENT '产品代码',
  `product_zh` VARCHAR(255) DEFAULT NULL COMMENT '产品中文名称',
  `project` VARCHAR(100) DEFAULT NULL COMMENT '项目',
  `project_display_name` VARCHAR(255) DEFAULT NULL COMMENT '项目中文名',
  `real_value` VARCHAR(50) DEFAULT NULL COMMENT '真实金额',
  `region` VARCHAR(100) DEFAULT NULL COMMENT '地域',
  `region_code` VARCHAR(50) DEFAULT NULL COMMENT '地域代码',
  `reservation_instance` VARCHAR(10) DEFAULT NULL COMMENT '预留实例',
  `round_amount` DECIMAL(20,6) DEFAULT NULL COMMENT '抹零金额',
  `saving_plan_deduction_discount_amount` VARCHAR(100) DEFAULT NULL COMMENT '节省计划抵扣金额',
  `saving_plan_deduction_sp_id` VARCHAR(100) DEFAULT NULL COMMENT '节省计划实例ID',
  `saving_plan_original_amount` DECIMAL(20,6) DEFAULT NULL COMMENT '节省计划抵扣原价',
  `seller_customer_name` VARCHAR(255) DEFAULT NULL COMMENT '销售方客户名称',
  `seller_id` VARCHAR(50) DEFAULT NULL COMMENT '销售方ID',
  `seller_user_name` VARCHAR(255) DEFAULT NULL COMMENT '销售方用户名',
  `selling_mode` VARCHAR(10) DEFAULT NULL COMMENT '销售模式',
  `settle_payable_amount` DECIMAL(20,6) DEFAULT NULL COMMENT '税后应付金额（结算币种）',
  `settle_posttax_amount` DECIMAL(20,6) DEFAULT NULL COMMENT '结算币种税后应付金额',
  `settle_pre_tax_payable_amount` DECIMAL(20,6) DEFAULT NULL COMMENT '税前应付金额（结算币种）',
  `settle_pretax_amount` DECIMAL(20,6) DEFAULT NULL COMMENT '结算币种税前应付金额',
  `settle_pretax_real_value` VARCHAR(100) DEFAULT NULL COMMENT '结算币种税前真实金额',
  `settle_real_value` VARCHAR(100) DEFAULT NULL COMMENT '结算币种真实金额',
  `settle_tax` DECIMAL(20,6) DEFAULT NULL COMMENT '结算币种税额',
  `settlement_type` VARCHAR(50) DEFAULT NULL COMMENT '结算类型',
  `solution_zh` VARCHAR(255) DEFAULT NULL COMMENT '解决方案中文名',
  `subject_name` VARCHAR(255) DEFAULT NULL COMMENT '主体名称',
  `tag` VARCHAR(500) DEFAULT NULL COMMENT '标签',
  `tax` DECIMAL(20,6) DEFAULT NULL COMMENT '税额',
  `tax_rate` DECIMAL(10,4) DEFAULT NULL COMMENT '税率',
  `trade_time` VARCHAR(20) DEFAULT NULL COMMENT '交易时间',
  `unit` VARCHAR(20) DEFAULT NULL COMMENT '用量单位',
  `unpaid_amount` DECIMAL(20,6) DEFAULT NULL COMMENT '未付金额',
  `use_duration` VARCHAR(20) DEFAULT NULL COMMENT '使用时长',
  `use_duration_unit` VARCHAR(20) DEFAULT NULL COMMENT '使用时长单位',
  `zone` VARCHAR(100) DEFAULT NULL COMMENT '可用区',
  `zone_code` VARCHAR(50) DEFAULT NULL COMMENT '可用区代码',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间,非api提供',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间,非api提供',
  PRIMARY KEY (`id`),
  INDEX `idx_bill_month_account` (`bill_month`,`owner_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS `account_info` (
  `id` int AUTO_INCREMENT NOT NULL ,
  `bill_account_id` varchar(50) NOT NULL COMMENT '账单所属账号ID',
  `bill_account_alias` varchar(50) NOT NULL COMMENT '账单所属账号别名',  
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_bill_account_id` (`bill_account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- cost_cny 原价-人民币， real_cost_cny  应付款-人民币， cash_pay_cny 现金支付-人民币, product_name 产品名称
CREATE OR REPLACE VIEW all_bill_resource_summary AS
select t1.bill_month ,t1.cloud, t2.bill_account_alias, t1.product_name, t1.cost_cny, t1.real_cost_cny, t1.cash_pay_cny from(
select bill_month, "aws" as cloud, bill_account_id, `service` as product_name, unblended_cost*exchange_rate as cost_cny, unblended_cost*exchange_rate as real_cost_cny, unblended_cost*exchange_rate as cash_pay_cny
from aws_bill_resource_summary
union all
select bill_month, "ucloud" as cloud, bill_account_id, `resource_type` as product_name, amount as cost_cny, amount_real as real_cost_cny, amount_real as cash_pay_cny  
from ucloud_bill_resource_summary
union all
select bill_month, "aliyun" as cloud, bill_account_id, product_name, pretax_gross_amount as cost_cny, pretax_amount as real_cost_cny, cash_amount as cash_pay_cny 
from aliyun_bill_resource_summary
union all
select bill_month, "volcengine" as cloud, `owner_id` as bill_account_id, product_zh as product_name, original_bill_amount as cost_cny, discount_bill_amount as real_cost_cny, payable_amount as cash_pay_cny 
from volcengine_bill_resource_summary
union all
select bill_month, "tencent" as cloud, `owner_uin` as bill_account_id, `business_code_name` as product_name, total_cost as cost_cny, real_total_cost as real_cost_cny, cash_pay_amount as cash_pay_cny
from tencent_bill_resource_summary) t1 
left join (select bill_account_alias,bill_account_id from account_info) t2 
on t1.bill_account_id = t2.bill_account_id;

