CREATE DATABASE `cloud_bill` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

use `cloud_bill`;

CREATE TABLE IF NOT EXISTS `aliyun_bill_resource_summary` (
  `id` int AUTO_INCREMENT NOT NULL ,
  `bill_month` datetime NULL COMMENT '账单归属月',
  `adjust_amount` decimal(18,8) NULL COMMENT '信用额度退款抵扣',
  `bill_account_id` varchar(50) NULL COMMENT '账单所属账号ID',
  `bill_account_name` varchar(50) NULL COMMENT '账单所属账号名称',
  `billing_date` datetime NULL COMMENT '账单日期',
  `billing_item` varchar(20) NULL COMMENT '计费项',
  `billing_item_code` varchar(20) NULL COMMENT '计费项代码',
  `billing_type` varchar(20) NULL COMMENT '计费方式',
  `biz_type` varchar(20) NULL COMMENT '业务类型',
  `cash_amount` decimal(18,8) NULL COMMENT '现金支付（不包含信用额度退款抵扣）',
  `commodity_code` varchar(50) NULL COMMENT '商品Code',
  `cost_unit` varchar(50) NULL COMMENT '财务单元',
  `currency` varchar(20) NULL COMMENT '币种',
  `deducted_by_cash_coupons` decimal(18,8) NULL COMMENT '代金券抵扣',
  `deducted_by_coupons` decimal(18,8) NULL COMMENT '优惠券优惠金额',
  `deducted_by_prepaid_card` decimal(18,8) NULL COMMENT '储值卡抵扣',
  `deducted_by_resource_package` varchar(255) NULL COMMENT '资源包抵扣',
  `instance_config` text NULL COMMENT '实例详细配置',
  `instance_id` varchar(100) NULL COMMENT '实例ID',
  `instance_spec` varchar(255) NULL COMMENT '实例规格',
  `internet_ip` varchar(50) NULL COMMENT '公网IP',
  `intranet_ip` varchar(50) NULL COMMENT '私网IP',
  `invoice_discount` decimal(18,8) NULL COMMENT '优惠金额',
  `item` varchar(20) NULL COMMENT '账单类型',
  `item_name` varchar(20) NULL COMMENT '项目名称',
  `list_price` decimal(18,8) NULL COMMENT '单价',
  `list_price_unit` varchar(20) NULL COMMENT '单价单位',
  `nick_name` varchar(50) NULL COMMENT '实例昵称',
  `outstanding_amount` decimal(18,8) NULL COMMENT '未结清金额',
  `owner_id` varchar(50) NULL COMMENT '资源Owner账号',
  `payment_amount` decimal(18,8) NULL COMMENT '现金支付（含信用额度退款抵扣）',
  `pip_code` varchar(50) NULL COMMENT '产品Code',
  `pretax_amount` decimal(18,8) NULL COMMENT '应付金额',
  `pretax_gross_amount` decimal(18,8) NULL COMMENT '原始金额',
  `discount` decimal(3,2) NULL COMMENT '折扣率：本资源享受的折扣率，接口未提供，计算公式：1-(pretax_amount/pretax_gross_amount)',
  `product_code` varchar(50) NULL COMMENT '产品代码',
  `product_detail` varchar(255) NULL COMMENT '产品明细',
  `product_name` varchar(50) NULL COMMENT '产品名称',
  `product_type` varchar(50) NULL COMMENT '产品类型',
  `region` varchar(100) NULL COMMENT '地域',
  `resource_group` varchar(50) NULL COMMENT '资源组',
  `service_period` int NULL COMMENT '服务时长',
  `service_period_unit` varchar(20) NULL COMMENT '服务时长单位',
  `subscription_type` varchar(20) NULL COMMENT '订阅类型(Subscription预付费,PayAsYouGo后付费)',
  `tag` varchar(255) NULL COMMENT '资源标签',
  `usage` decimal(18,8) NULL COMMENT '用量',
  `usage_unit` varchar(20) NULL COMMENT '用量单位',
  `zone` varchar(50) NULL COMMENT '可用区',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_bill_id` (`bill_month`,`bill_account_id`,`product_code`,`product_detail`,`instance_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- CREATE UNIQUE INDEX idx_bill_id ON aliyun_bill_resource_summary (`bill_month`,`bill_account_id`,`product_code`,`product_detail`,`instance_id`);


CREATE TABLE IF NOT EXISTS `tencent_bill_resource_summary` (
  `id` int AUTO_INCREMENT NOT NULL ,
  `bill_month` datetime NULL COMMENT '账单归属月',
  `tags` json NULL COMMENT '标签信息，注意：此字段可能返回 null，表示取不到有效值。',
  `action_type_name` varchar(50) NULL COMMENT '交易类型：如包年包月新购、包年包月续费、按量计费扣费等类型',
  `business_code` varchar(50) NULL COMMENT '产品编码',
  `business_code_name` varchar(100) NULL COMMENT '产品名称：用户所采购的各类云产品，例如：云服务器 CVM',
  `cash_pay_amount` decimal(18,8) NULL COMMENT '现金账户支出：通过现金账户支付的金额',
  `config_desc` varchar(255) NULL COMMENT '配置描述：该资源下的计费项名称和用量合并展示，仅在资源账单体现',
  `discount` decimal(3,2) NULL COMMENT '折扣率：本资源享受的折扣率（如果客户享受一口价/合同价则默认不展示，退费场景也默认不展示）',
  `extend_field1` varchar(255) NULL COMMENT '扩展字段1：产品对应的扩展属性信息，仅在资源账单体现',
  `extend_field2` varchar(255) NULL COMMENT '扩展字段2：产品对应的扩展属性信息，仅在资源账单体现',
  `extend_field3` varchar(255) NULL COMMENT '扩展字段3：产品对应的扩展属性信息，仅在资源账单体现',
  `extend_field4` varchar(255) NULL COMMENT '扩展字段4：产品对应的扩展属性信息，仅在资源账单体现',
  `extend_field5` varchar(255) NULL COMMENT '扩展字段5：产品对应的扩展属性信息，仅在资源账单体现',
  `fee_begin_time` datetime NULL COMMENT '开始使用时间：产品服务开始使用时间',
  `fee_end_time` datetime NULL COMMENT '结束使用时间：产品服务结束使用时间',
  `incentive_pay_amount` decimal(18,8) NULL COMMENT '赠送账户支出：使用赠送金支付的金额',
  `instance_type` varchar(50) NULL COMMENT '实例类型：购买的产品服务对应的实例类型，包括资源包、RI、SP、竞价实例。正常的实例展示默认为不展示',
  `operate_uin` varchar(30) NULL COMMENT '操作者UIN：操作者账号 ID（预付费资源下单或后付费操作开通资源账号的 ID 或者角色 ID ）',
  `order_id` varchar(30) NULL COMMENT '订单ID：包年包月计费模式下订购的订单号',
  `original_cost_with_ri` decimal(18,8) NULL COMMENT '预留实例抵扣组件原价：本产品或服务使用预留实例抵扣的组件原价金额',
  `original_cost_with_sp` decimal(18,8) NULL COMMENT '节省计划抵扣组件原价：节省计划抵扣原价=节省计划包抵扣金额/节省计划抵扣率',
  `owner_uin` varchar(30) NULL COMMENT '使用者UIN：实际使用资源的账号 ID',
  `pay_mode_name` varchar(20) NULL COMMENT '计费模式：资源的计费模式，区分为包年包月和按量计费',
  `pay_time` datetime NULL COMMENT '扣费时间：结算扣费时间',
  `payer_uin` varchar(30) NULL COMMENT '支付者UIN：支付者的账号 ID，账号 ID 是用户在腾讯云的唯一账号标识',
  `product_code` varchar(50) NULL COMMENT '子产品编码',
  `product_code_name` varchar(100) NULL COMMENT '子产品名称：用户采购的具体产品细分类型，例如：云服务器 CVM-标准型 S1',
  `project_name` varchar(50) NULL COMMENT '项目名称：资源归属的项目，用户在控制台给资源自主分配项目，未分配则是默认项目',
  `real_total_cost` decimal(18,8) NULL COMMENT '优惠后总价',
  `reduce_type` varchar(20) NULL COMMENT '优惠类型',
  `region_id` int NULL COMMENT '地域ID',
  `region_name` varchar(100) NULL COMMENT '地域：资源所属地域，如华南地区（广州）',
  `resource_id` varchar(255) NULL COMMENT '资源 ID：账单中出账对象 ID，不同产品因资源形态不同，资源内容不完全相同，如云服务器 CVM 为对应的实例 ID',
  `resource_name` varchar(255) NULL COMMENT '资源别名：用户在控制台为资源设置的名称，如果未设置，则默认为空',
  `total_cost` decimal(18,8) NULL COMMENT '原价：原价 = 组件刊例价 * 组件用量 * 使用时长（如果客户享受一口价/合同价则默认不展示，退费类场景也默认不展示）',
  `transfer_pay_amount` decimal(18,8) NULL COMMENT '分成金账户支出：通过分成金账户支付的金额,注意：此字段可能返回 null，表示取不到有效值。',
  `voucher_pay_amount` decimal(18,8) NULL COMMENT '优惠券支出：使用各类优惠券（如代金券、现金券等）支付的金额',
  `zone_name` varchar(50) NULL COMMENT '可用区：资源所属可用区，如广州三区',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_bill_id` (`bill_month`,`payer_uin`,`business_code`,`product_code`,`resource_id`,`order_id`,`config_desc`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- CREATE UNIQUE INDEX idx_bill_id ON tencent_bill_resource_summary (`bill_month`,`payer_uin`,`business_code`,`product_code`,`resource_id`,`order_id`,`config_desc`);


CREATE TABLE IF NOT EXISTS `ucloud_bill_resource_summary` (
  `id` int AUTO_INCREMENT NOT NULL ,
  `bill_month` datetime NULL COMMENT '账单归属月',
  `admin` int NULL COMMENT '是否为主账号',
  `amount` decimal(18,8) NULL COMMENT '订单总金额',
  `amount_coupon` decimal(18,8) NULL COMMENT '代金券抵扣',
  `amount_free` decimal(18,8) NULL COMMENT '赠送金额抵扣',
  `amount_real` decimal(18,8) NULL COMMENT '现金账户支付',
  `az_group_c_name` varchar(50) NULL COMMENT '可用区',
  `charge_type` varchar(50) NULL COMMENT '计费方式: Year按年,Month按月,Day按天,Dynamic按时,Used按量,Donate赠送,Trial试用,Post后付费,Spot抢占式',
  `create_time` datetime NULL COMMENT '创建时间',
  `item_details` varchar(255) NULL COMMENT '产品配置',
  `order_no` varchar(50) NULL COMMENT '订单号',
  `order_type` varchar(50) NULL COMMENT '订单类型: OT_BUY新购,OT_RENEW续费,OT_UPGRADE升级,OT_DOWNGRADE降级,OT_SUSPEND结算,OT_ADDITIONAL补单  OT_REFUND删除,OT_POSTPAID_RENEW过期,OT_POSTPAID_PAYMENT后付费,OT_RECOVER删除恢复',
  `project_name` varchar(50) NULL COMMENT '项目名称',
  `resource_extend_info` varchar(255) NULL COMMENT '资源标识',
  `resource_id` varchar(50) NULL COMMENT '资源ID',
  `resource_type` varchar(50) NULL COMMENT '产品类型: uhost云主机,udisk普通云硬盘,udb云数据库,eip弹性IP,ufile对象存储,fortress_host堡垒机  ufs文件存储,wafWEB应用防火墙,ues弹性搜索,udisk_ssdSSD云硬盘,rssdRSSD云硬盘',
  `resource_type_code` int NULL COMMENT '产品类型代码',
  `show_hover` int NULL COMMENT '订单支付状态: 0未支付,1已支付',
  `start_time` datetime NULL COMMENT '开始时间',
  `user_display_name` varchar(50) NULL COMMENT '账户昵称',
  `user_email` varchar(50) NULL COMMENT '账户邮箱',
  `user_name` varchar(50) NULL COMMENT '账户名',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
