{
 "title": "AWS账单详情",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "数据源", "query": "mysql" },
   {
    "name": "bill_month",
    "label": "账单月份",
    "query": "select  distinct(date_format(bill_month,'%Y-%m')) from aws_bill_resource_summary "
   },
   {
    "name": "bill_account",
    "label": "账户",
    "query": "select  distinct(bill_account_id) from aws_bill_resource_summary  union select \"空\""
   }
  ]
 },
 "panels": [
  { "title": "成本趋势", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "云产品应付款上月环比（负数即下降，正数即上升），请忽略第一个月份的数据",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",service,\r\n  (CASE WHEN DATE_FORMAT(bill_month,'%Y-%m-%d') >= DATE_FORMAT(FROM_UNIXTIME(${__from}/1000) + INTERVAL 1 MONTH, '%Y-%m-15') THEN (sum(unblended_cost)  - (lag(sum(unblended_cost),1,0) over (partition by service order by bill_month))) ELSE 0 END) as \"上月环比\"\r\nfrom aws_bill_resource_summary\r\nwhere $__timeFilter(bill_month) and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month,service\r\norder by bill_month"
    }
   ]
  },
  {
   "title": "云产品应付款",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",service,\r\nsum(unblended_cost) as \"应付款\"\r\nfrom aws_bill_resource_summary\r\nwhere $__timeFilter(bill_month) and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month,service\r\norder by bill_month"
    }
   ]
  },
  { "title": "月账单详情", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "月成本(汇率默认按7.0计算)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",sum(unblended_cost) as \"应付款-美元\",sum(unblended_cost*exchange_rate) as \"应付款-人民币\"\r\nfrom aws_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month"
    }
   ]
  },
  {
   "title": "产品分类成本占比",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",service,sum(unblended_cost) as \"应付款\" \r\nfrom aws_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month,service"
    }
   ]
  },
  {
   "title": "地域成本占比",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 13, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",region,sum(unblended_cost) as \"应付款\" \r\nfrom aws_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month,region"
    }
   ]
  },
  {
   "title": "产品分类成本",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",service,sum(unblended_cost) as \"应付款\" \r\nfrom aws_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month,service\r\n"
    }
   ]
  }
 ]
}