{
 "title": "UCloud账单详情",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "数据源", "query": "mysql" },
   {
    "name": "bill_month",
    "label": "账单月份",
    "query": "select  distinct(date_format(bill_month,'%Y-%m')) from ucloud_bill_resource_summary "
   },
   {
    "name": "bill_account",
    "label": "账户",
    "query": "select  distinct(bill_account_id) from ucloud_bill_resource_summary  union select \"空\""
   }
  ]
 },
 "panels": [
  { "title": "成本趋势", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "云产品应付款上月环比（负数即下降，正数即上升），请忽略第一个月份的数据",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",resource_type,\r\n  (CASE WHEN DATE_FORMAT(bill_month,'%Y-%m-%d') >= DATE_FORMAT(FROM_UNIXTIME(${__from}/1000) + INTERVAL 1 MONTH, '%Y-%m-15') THEN (sum(amount_real)  - (lag(sum(amount_real),1,0) over (partition by resource_type order by bill_month))) ELSE 0 END) as \"上月环比\"\r\nfrom ucloud_bill_resource_summary\r\nwhere $__timeFilter(bill_month) and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month,resource_type\r\norder by bill_month"
    }
   ]
  },
  {
   "title": "云产品应付款",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",resource_type,\r\nsum(amount_real) as \"应付款\"\r\nfrom ucloud_bill_resource_summary\r\nwhere $__timeFilter(bill_month) and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month,resource_type\r\norder by bill_month"
    }
   ]
  },
  { "title": "月账单详情", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "月成本",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",sum(amount_real) as \"应付款\",sum(amount) as \"原价\" \r\nfrom ucloud_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month"
    }
   ]
  },
  {
   "title": "总体折扣率",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",sum(amount_real)/sum(amount) as \"折扣率\" \r\nfrom ucloud_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month"
    }
   ]
  },
  {
   "title": "产品分类成本占比",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",resource_type,sum(amount_real) as \"应付款\" \r\nfrom ucloud_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month,resource_type"
    }
   ]
  },
  {
   "title": "地域成本占比",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",az_group_c_name,sum(amount_real) as \"应付款\" \r\nfrom ucloud_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month,az_group_c_name"
    }
   ]
  },
  {
   "title": "计费模式成本占比",
   "type": "piechart",
   "description": "计费方式: Year按年,Month按月,Day按天,Dynamic按时,Used按量,Donate赠送,Trial试用,Post后付费,Spot抢占式",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",charge_type,sum(amount_real) as \"应付款\" \r\nfrom ucloud_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month,charge_type"
    }
   ]
  },
  {
   "title": "产品分类成本",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",resource_type,sum(amount_real) as \"应付款\" \r\nfrom ucloud_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month,resource_type\r\n"
    }
   ]
  },
  {
   "title": "资源列表",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",resource_type as \"产品名称\",charge_type as \"计费模式\",item_details as \"产品配置\",az_group_c_name as \"地域\",resource_id as \"资源id\",order_type as \"订单类型\",amount as \"原价\",amount_real as \"优惠后总价\" \r\nfrom ucloud_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and bill_account_id = \"${bill_account}\""
    }
   ]
  }
 ]
}