{
 "title": "云平台账单半年趋势",
 "time": { "from": "now-7M", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "数据源", "query": "mysql" }
  ]
 },
 "panels": [
  { "title": "云账户汇总", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "云平台每月应付款",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  bill_month AS \"time\",\n  bill_account_alias,\n  sum(real_cost_cny) as \"应付款-\"\nFROM all_bill_resource_summary\nWHERE\n  $__timeFilter(bill_month)\ngroup by bill_month,bill_account_alias\nORDER BY bill_month"
    },
    {
     "rawSql": "SELECT\n  bill_month AS \"time\",\n  sum(real_cost_cny) as \"应付款-合计\"\nFROM all_bill_resource_summary\nWHERE\n  $__timeFilter(bill_month)\ngroup by bill_month\nORDER BY bill_month"
    }
   ]
  },
  {
   "title": "云平台每月应付款占比",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  bill_month AS \"time\",\n  bill_account_alias,\n  sum(real_cost_cny) as \"应付款-\"\nFROM all_bill_resource_summary\nWHERE\n  $__timeFilter(bill_month)\ngroup by bill_month,bill_account_alias\nORDER BY bill_month"
    }
   ]
  },
  {
   "title": "云平台应付款上月环比（负数即下降，正数即上升），请忽略第一个月份的数据",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  bill_month AS \"time\",\r\n  bill_account_alias,\r\n  (CASE WHEN DATE_FORMAT(bill_month,'%Y-%m-%d') >= DATE_FORMAT(FROM_UNIXTIME(${__from}/1000) + INTERVAL 1 MONTH, '%Y-%m-15') THEN (sum(real_cost_cny)  - (lag(sum(real_cost_cny),1,0) over (partition by bill_account_alias order by bill_month))) ELSE 0 END)\r\n   as \"上月环比\"\r\nFROM all_bill_resource_summary\r\nWHERE\r\n  $__timeFilter(bill_month)\r\ngroup by bill_month,bill_account_alias\r\nORDER BY bill_month"
    }
   ]
  },
  {
   "title": "云平台每月应付款",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  bill_month AS \"time\",\n  bill_account_alias,\n  sum(real_cost_cny) as \"应付款-\"\nFROM all_bill_resource_summary\nWHERE\n  $__timeFilter(bill_month)\ngroup by bill_month,bill_account_alias\nORDER BY bill_month"
    }
   ]
  },
  { "title": "云平台汇总", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "云平台每月应付款",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  bill_month AS \"time\",\n  cloud,\n  sum(real_cost_cny) as \"应付款-\"\nFROM all_bill_resource_summary\nWHERE\n  $__timeFilter(bill_month)\ngroup by bill_month,cloud\nORDER BY bill_month"
    },
    {
     "rawSql": "SELECT\n  bill_month AS \"time\",\n  sum(real_cost_cny) as \"应付款-合计\"\nFROM all_bill_resource_summary\nWHERE\n  $__timeFilter(bill_month)\ngroup by bill_month\nORDER BY bill_month"
    }
   ]
  },
  {
   "title": "云平台每月应付款占比",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "SELECT\n  bill_month AS \"time\",\n  cloud,\n  sum(real_cost_cny) as \"应付款-\"\nFROM all_bill_resource_summary\nWHERE\n  $__timeFilter(bill_month)\ngroup by bill_month,cloud\nORDER BY bill_month"
    }
   ]
  }
 ]
}