{
 "title": "火山引擎账单详情",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "数据源", "query": "mysql" },
   {
    "name": "bill_month",
    "label": "账单月份",
    "query": "select  distinct(date_format(bill_month,'%Y-%m')) from volcengine_bill_resource_summary"
   },
   {
    "name": "bill_account",
    "label": "账户",
    "query": "select  distinct(owner_id) from volcengine_bill_resource_summary union select \"空\""
   }
  ]
 },
 "panels": [
  { "title": "成本趋势", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "云产品应付款上月环比（负数即下降，正数即上升），请忽略第一个月份的数据",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",product_zh,\r\n  (CASE WHEN DATE_FORMAT(bill_month,'%Y-%m-%d') >= DATE_FORMAT(FROM_UNIXTIME(${__from}/1000) + INTERVAL 1 MONTH, '%Y-%m-15') THEN (sum(discount_bill_amount)  - (lag(sum(discount_bill_amount),1,0) over (partition by product_zh order by bill_month))) ELSE 0 END) as \"上月环比\"\r\nfrom volcengine_bill_resource_summary\r\nwhere $__timeFilter(bill_month) and owner_id = \"${bill_account}\"\r\ngroup by bill_month,product_zh\r\norder by bill_month"
    }
   ]
  },
  {
   "title": "云产品应付款",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",product_zh,\r\nsum(discount_bill_amount) as \"应付款\"\r\nfrom volcengine_bill_resource_summary\r\nwhere $__timeFilter(bill_month) and owner_id = \"${bill_account}\"\r\ngroup by bill_month,product_zh\r\norder by bill_month"
    }
   ]
  },
  {
   "title": "云产品优惠券抵扣",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",product_zh,\r\nsum(coupon_amount) as \"优惠券支出\"\r\nfrom volcengine_bill_resource_summary\r\nwhere $__timeFilter(bill_month) and owner_id = \"${bill_account}\"\r\ngroup by bill_month,product_zh\r\norder by bill_month"
    },
    {
     "rawSql": "select bill_month as \"time\",\r\nsum(coupon_amount) as \"优惠券合计支出\"\r\nfrom volcengine_bill_resource_summary\r\nwhere $__timeFilter(bill_month) and owner_id = \"${bill_account}\"\r\ngroup by bill_month\r\norder by bill_month"
    }
   ]
  },
  { "title": "月账单详情", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "月成本",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 15, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",sum(discount_bill_amount) as \"应付款\",sum(original_bill_amount) as \"原价\" \r\nfrom volcengine_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and owner_id = \"${bill_account}\"\r\ngroup by bill_month"
    }
   ]
  },
  {
   "title": "支出分类",
   "type": "bargauge",
   "description": "优惠券支出：使用各类优惠券（如代金券、现金券等）支付的金额",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",sum(payable_amount) as \"现金支出\",sum(coupon_amount) as \"优惠券支出\" \r\nfrom volcengine_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and owner_id = \"${bill_account}\"\r\ngroup by bill_month"
    }
   ]
  },
  {
   "title": "总体折扣率",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",sum(discount_bill_amount)/sum(original_bill_amount) as \"折扣率\" \r\nfrom volcengine_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and owner_id = \"${bill_account}\"\r\ngroup by bill_month"
    }
   ]
  },
  {
   "title": "产品分类成本占比",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",product_zh,sum(discount_bill_amount) as \"应付款\" \r\nfrom volcengine_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and owner_id = \"${bill_account}\"\r\ngroup by bill_month,product_zh"
    }
   ]
  },
  {
   "title": "地域成本占比",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",region,sum(discount_bill_amount) as \"应付款\" \r\nfrom volcengine_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and owner_id = \"${bill_account}\"\r\ngroup by bill_month,region"
    }
   ]
  },
  {
   "title": "计费模式成本占比",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",billing_mode,sum(discount_bill_amount) as \"应付款\" \r\nfrom volcengine_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and owner_id = \"${bill_account}\"\r\ngroup by bill_month,billing_mode"
    }
   ]
  },
  {
   "title": "产品分类成本占比-包年包月",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",product_zh,sum(discount_bill_amount) as \"应付款\" \r\nfrom volcengine_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and owner_id = \"${bill_account}\" and billing_mode=\"包年包月\"\r\ngroup by bill_month,product_zh"
    }
   ]
  },
  {
   "title": "产品分类成本占比-按量计费",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",product_zh,sum(discount_bill_amount) as \"应付款\" \r\nfrom volcengine_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and owner_id = \"${bill_account}\" and billing_mode=\"按量计费\"\r\ngroup by bill_month,product_zh"
    }
   ]
  },
  {
   "title": "产品分类成本",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",product_zh,sum(discount_bill_amount) as \"应付款\" \r\nfrom volcengine_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and owner_id = \"${bill_account}\"\r\ngroup by bill_month,product_zh\r\n"
    }
   ]
  },
  {
   "title": "产品折扣(-为不打折，0为免费，0.7为打7折)",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",product_zh as \"产品名称\",billing_mode as \"计费模式\",bill_category as \"账单类别\",element as \"计费单元\",factor_code as \"实例规格\" ,region as \"地域\",discount_biz_unit_price as \"折扣率\",count(*) as 数量 \r\nfrom volcengine_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and owner_id = \"${bill_account}\"\r\ngroup by bill_month,product_zh,billing_mode,bill_category,element,factor_code,region,discount_biz_unit_price\r\norder by discount_biz_unit_price asc,product_zh asc,billing_mode asc,element asc,factor_code asc,region asc"
    }
   ]
  },
  {
   "title": "资源列表",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",instance_no as \"实例ID\",instance_name as \"实例名称\",product_zh as \"产品名称\",region as \"地域\",zone as \"可用区\",`count` as \"用量\",discount_biz_unit_price as \"折扣率\",original_bill_amount as \"原价\",discount_bill_amount as \"优惠后总价\" ,billing_mode as \"计费模式\",bill_category as \"账单类别\",element as \"计费单元\",factor_code as \"实例规格\",discount_biz_billing_function as \"优惠类型\"\r\nfrom volcengine_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and owner_id = \"${bill_account}\""
    }
   ]
  }
 ]
}