{
 "title": "腾讯云账单详情",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "数据源", "query": "mysql" },
   {
    "name": "bill_month",
    "label": "账单月份",
    "query": "select  distinct(date_format(bill_month,'%Y-%m')) from tencent_bill_resource_summary "
   },
   {
    "name": "bill_account",
    "label": "账户",
    "query": "select  distinct(owner_uin) from tencent_bill_resource_summary  union select \"空\""
   }
  ]
 },
 "panels": [
  { "title": "成本趋势", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "云产品应付款上月环比（负数即下降，正数即上升），请忽略第一个月份的数据",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",business_code_name,\r\n  (CASE WHEN DATE_FORMAT(bill_month,'%Y-%m-%d') >= DATE_FORMAT(FROM_UNIXTIME(${__from}/1000) + INTERVAL 1 MONTH, '%Y-%m-15') THEN (sum(real_total_cost)  - (lag(sum(real_total_cost),1,0) over (partition by business_code_name order by bill_month))) ELSE 0 END) as \"上月环比\"\r\nfrom tencent_bill_resource_summary\r\nwhere $__timeFilter(bill_month) and owner_uin = \"${bill_account}\"\r\ngroup by bill_month,business_code_name\r\norder by bill_month"
    }
   ]
  },
  {
   "title": "云产品应付款",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",business_code_name,\r\nsum(real_total_cost) as \"应付款\"\r\nfrom tencent_bill_resource_summary\r\nwhere $__timeFilter(bill_month) and owner_uin = \"${bill_account}\"\r\ngroup by bill_month,business_code_name\r\norder by bill_month"
    }
   ]
  },
  {
   "title": "云产品优惠券抵扣",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",business_code_name,\r\nsum(voucher_pay_amount) as \"优惠券支出\"\r\nfrom tencent_bill_resource_summary\r\nwhere $__timeFilter(bill_month) and owner_uin = \"${bill_account}\"\r\ngroup by bill_month,business_code_name\r\norder by bill_month"
    },
    {
     "rawSql": "select bill_month as \"time\",\r\nsum(voucher_pay_amount) as \"优惠券合计支出\"\r\nfrom tencent_bill_resource_summary\r\nwhere $__timeFilter(bill_month) and owner_uin = \"${bill_account}\"\r\ngroup by bill_month\r\norder by bill_month"
    }
   ]
  },
  { "title": "月账单详情", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "月成本",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 15, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",sum(real_total_cost) as \"应付款\",sum(total_cost) as \"原价\" \r\nfrom tencent_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and owner_uin = \"${bill_account}\"\r\ngroup by bill_month"
    }
   ]
  },
  {
   "title": "支出分类",
   "type": "bargauge",
   "description": "优惠券支出：使用各类优惠券（如代金券、现金券等）支付的金额",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",sum(cash_pay_amount) as \"现金支出\",sum(voucher_pay_amount) as \"优惠券支出\" \r\nfrom tencent_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and owner_uin = \"${bill_account}\"\r\ngroup by bill_month"
    }
   ]
  },
  {
   "title": "总体折扣率",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",sum(real_total_cost)/sum(total_cost) as \"折扣率\" \r\nfrom tencent_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and owner_uin = \"${bill_account}\"\r\ngroup by bill_month"
    }
   ]
  },
  {
   "title": "产品分类成本占比",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",business_code_name,sum(real_total_cost) as \"应付款\" \r\nfrom tencent_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and owner_uin = \"${bill_account}\"\r\ngroup by bill_month,business_code_name"
    }
   ]
  },
  {
   "title": "地域成本占比",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",region_name,sum(real_total_cost) as \"应付款\" \r\nfrom tencent_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and owner_uin = \"${bill_account}\"\r\ngroup by bill_month,region_name"
    }
   ]
  },
  {
   "title": "计费模式成本占比",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",pay_mode_name,sum(real_total_cost) as \"应付款\" \r\nfrom tencent_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and owner_uin = \"${bill_account}\"\r\ngroup by bill_month,pay_mode_name"
    }
   ]
  },
  {
   "title": "产品分类成本",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",business_code_name,sum(real_total_cost) as \"应付款\" \r\nfrom tencent_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and owner_uin = \"${bill_account}\"\r\ngroup by bill_month,business_code_name\r\n\r\n"
    }
   ]
  },
  {
   "title": "产品折扣(1为不打折，0为免费，0.7为打7折)",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",business_code_name as \"产品名称\",pay_mode_name as \"计费模式\",product_code_name as \"子产品名称\",config_desc as \"配置描述\",instance_type as \"实例类型\",region_name as \"地域\",action_type_name as \"交易类型\",avg(discount) as \"折扣率\" \r\nfrom tencent_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and owner_uin = \"${bill_account}\"\r\ngroup by bill_month,business_code_name,pay_mode_name,product_code_name,config_desc,instance_type,region_name,action_type_name\r\norder by bill_month desc,business_code_name asc,pay_mode_name asc,product_code_name asc,config_desc asc,instance_type asc,region_name asc,action_type_name asc"
    }
   ]
  },
  {
   "title": "资源列表",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",business_code_name as \"产品名称\",pay_mode_name as \"计费模式\",product_code_name as \"子产品名称\",config_desc as \"配置描述\",instance_type as \"实例类型\",region_name as \"地域\",resource_id as \"资源id\",action_type_name as \"交易类型\",reduce_type as \"优惠类型\",discount as \"折扣率\",total_cost as \"原价\",real_total_cost as \"优惠后总价\" \r\nfrom tencent_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and owner_uin = \"${bill_account}\"\r\n"
    }
   ]
  }
 ]
}