{
 "title": "阿里云账单详情",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "数据源", "query": "mysql" },
   {
    "name": "bill_month",
    "label": "账单月份",
    "query": "select  distinct(date_format(bill_month,'%Y-%m')) from aliyun_bill_resource_summary "
   },
   {
    "name": "bill_account",
    "label": "账户",
    "query": "select  distinct(bill_account_id) from aliyun_bill_resource_summary  union select \"空\""
   }
  ]
 },
 "panels": [
  { "title": "成本趋势", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "云产品应付款上月环比（负数即下降，正数即上升），请忽略第一个月份的数据",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",product_name,\r\n  (CASE WHEN DATE_FORMAT(bill_month,'%Y-%m-%d') >= DATE_FORMAT(FROM_UNIXTIME(${__from}/1000) + INTERVAL 1 MONTH, '%Y-%m-15') THEN (sum(pretax_amount)  - (lag(sum(pretax_amount),1,0) over (partition by product_name order by bill_month))) ELSE 0 END) as \"上月环比\"\r\nfrom aliyun_bill_resource_summary\r\nwhere $__timeFilter(bill_month) and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month,product_name\r\norder by bill_month"
    }
   ]
  },
  {
   "title": "云产品应付款",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",product_name,\r\nsum(pretax_amount) as \"应付款\"\r\nfrom aliyun_bill_resource_summary\r\nwhere $__timeFilter(bill_month) and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month,product_name\r\norder by bill_month"
    }
   ]
  },
  { "title": "月账单详情", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "月成本",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 19, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",sum(pretax_amount) as \"应付款\",sum(pretax_gross_amount) as \"原价\" \r\nfrom aliyun_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month"
    }
   ]
  },
  {
   "title": "总体折扣率(不包括阿里云短信优惠)",
   "type": "stat",
   "description": "阿里云短信优惠在账单看不出来，只能到短信服务的计费查看",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",sum(pretax_amount)/sum(pretax_gross_amount) as \"折扣率\" \r\nfrom aliyun_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month"
    }
   ]
  },
  {
   "title": "产品分类成本占比",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",product_name,sum(pretax_amount) as \"应付款\" \r\nfrom aliyun_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month,product_name"
    }
   ]
  },
  {
   "title": "地域成本占比(短信和语音地域为1)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",region,sum(pretax_amount) as \"应付款\" \r\nfrom aliyun_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month,region"
    }
   ]
  },
  {
   "title": "计费模式成本占比(Subscription预付费,PayAsYouGo后付费)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",subscription_type,sum(pretax_amount) as \"应付款\" \r\nfrom aliyun_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month,subscription_type"
    }
   ]
  },
  {
   "title": "产品分类成本",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",product_name,sum(pretax_amount) as \"应付款\" \r\nfrom aliyun_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month,product_name\r\n\r\n"
    }
   ]
  },
  {
   "title": "产品折扣(1为不打折，0为免费，0.7为打7折)",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",product_name as \"产品名称\",subscription_type as \"计费模式\",instance_spec as \"实例规格\",instance_config as \"实例详细配置\",region as \"地域\",item as \"账单类型\",avg(discount) as \"折扣率\" \r\nfrom aliyun_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and bill_account_id = \"${bill_account}\"\r\ngroup by bill_month,product_name,subscription_type,instance_spec,instance_config,region,item\r\norder by bill_month desc,product_name asc,subscription_type asc,instance_spec asc,instance_config asc,region asc,item asc"
    }
   ]
  },
  {
   "title": "资源列表",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select bill_month as \"time\",product_name as \"产品名称\",subscription_type as \"计费模式\",instance_spec as \"实例规格\",instance_config as \"实例详细配置\",region as \"地域\",instance_id as \"资源id\",item as \"账单类型\",discount as \"折扣率\",pretax_gross_amount as \"原价\",pretax_amount as \"优惠后总价\" \r\nfrom aliyun_bill_resource_summary\r\nwhere date_format(bill_month,'%Y-%m') = \"${bill_month}\" and bill_account_id = \"${bill_account}\""
    }
   ]
  }
 ]
}